### ISSUE TITLE
bug(recipe): transformation risks disrupting these (feature, label) pairings.

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#150]
Databases may return rows in an indeterminate order, but it's essential to preserve the (feature, label) row alignment during ML training. The current transformation risks disrupting these (feature, label) pairings.

for example
```
X_train 
┏━━━━━━━┳━━━━━━━━┓
┃ time  ┃ ticker ┃
┡━━━━━━━╇━━━━━━━━┩
│ int64 │ string │
├───────┼────────┤
│     0 │ GOOG   │
│     1 │ NULL   │
│     2 │ MSFT   │
│     3 │ MSFT   │
│     4 │ NULL   │
│     5 │ AAPL   │
│     6 │ GOOG   │
│     7 │ NULL   │
└───────┴────────┘

y_train
┏━━━━━━━┓
┃ label ┃
┡━━━━━━━┩
│ int64 │
├───────┤
│     0 │
│     1 │
│     2 │
│     3 │
│     4 │
│     5 │
│     6 │
│     7 │
└───────┘
```

we need to maintain this order after all X_train transformation.

For example, after running this transformation

```python
import ibis
import ibis_ml as ml

ibis.options.interactive = True

t_train = ibis.memtable(
    {
        "time": range(8),
        "ticker": ["GOOG", None, "MSFT", "MSFT", None, "AAPL", "GOOG", None],
        "label": range(8),
    }
)

r = ml.Recipe(
    ml.OrdinalEncode("ticker")
)

X_train = t_train.drop("label")
y_train = t_train["label"]

y_train_preprocessed = r.fit(X_train, y_train).to_ibis(X_train)
```
y_train_preprocessed row order is changed.

```
y_train_preprocessed

┏━━━━━━━┳━━━━━━━━┓
┃ time  ┃ ticker ┃
┡━━━━━━━╇━━━━━━━━┩
│ int64 │ int64  │
├───────┼────────┤
│     0 │      1 │
│     2 │      2 │
│     3 │      2 │
│     5 │      0 │
│     6 │      1 │
│     1 │   NULL │
│     4 │   NULL │
│     7 │   NULL │
└───────┴────────┘
```

We need to enforce `maintain_order = True`  in the recipe transformation to maintain the order

**Comment by jcrist** [comment]
Maintaining order in the database is expensive. To handle this, there are two patterns in ibis-ml:

- If in-memory data (numpy/pandas/pyarrow/whatever) is passed to `transform`/`to_*` methods, the output order will match the input order. Since the data was already in-memory, it's naturally small in size, and order will be cheaper to maintain. This is also needed to fit into existing `sklearn` pipelines which have an expectation of maintaining row order in transforms.
- If an ibis `Table` is passed to `transform`/`to_*` methods, the row ordering is not maintained (as you've noted). This lets us avoid expensive ordering. However, extra columns passed to `transform`/`to_*` are passed through unchanged. The intended workflow here is to split `X`/`y` _after_ passing them to `transform`/`to_*` so that the rows are still aligned. This is cheap and requires just a slight rearrangement of calls:

```python
X_train = t_train.drop("label")
y_train = t_train["label"]

# Fit on the training dataset
# Note that in pretty much all cases `y_train` is ignored
r.fit(X_train, y_train)

# Apply the fit recipe to the whole table
t_train_preprocessed = r.to_ibis(t_train)

# Then split into X and y afterwards, maintaining row ordering
X_train_preprocessed = t_train_preprocessed.drop("label")
y_train_preprocessed = t_train_preprocessed["label"]
```

The internals code for maintaining ordering is in `normalize_table` (see https://github.com/ibis-project/ibis-ml/blob/2f2aaafea31e4ca0ccf9ef2e001ac4e7717d674b/ibis_ml/core.py#L59).

Closing as intentional.
