### ISSUE TITLE
doc: ibisml for sklearn/Tidymodel users tutorial sessions

### ISSUE THREAD

**Issue by jitingxu1** [ibis-project/ibis-ml#59]
It's really important to make sure that ibisml is user-friendly for people who are already familiar with scikit-learn and tidymodel. Adding coverage of scikit-learn and sklearn preprocessing in the documentation and tutorials will make it easier for python and R users to start using ibisml.

In this tutorial or documentation, we should cover the following points:

- Mapping scikit-learn and Tidymodel preprocessing techniques directly to ibisml equivalents.
- Providing examples of ibisml preprocessing, which can be taken from the API reference documentation.
- [Optional] Demonstrating how to integrate ibisml preprocessing with scikit-learn and tidymodels. This was partly covered in the main tutorial, but we can expand on it if needed.

Also need to combine this #30

**Comment by deepyaman** [comment]
> * Mapping scikit-learn and Tidymodel preprocessing techniques directly to ibisml equivalents.

I think this is covered by #30, and is more to track IbisML development priorities and progress, rather than necessarily surfacing to users in a tutorial (I imagine most DS can figure out if they need to use `ImputeMean` vs `SimpleImputer(strategy="mean")`.

For tracking purposes, I feel like https://github.com/ibis-project/ibis-ml/issues/32 is sufficient for now.

> * Providing examples of ibisml preprocessing, which can be taken from the API reference documentation.
> * [Optional] Demonstrating how to integrate ibisml preprocessing with scikit-learn and tidymodels. This was partly covered in the main tutorial, but we can expand on it if needed.

I think a single demo workflow could cover this for now, because it's being integrated in scikit-learn pipeline anyway, and the syntax should be fairly familiar for people coming from tidymodels.
